services:
  ui:
    build: 
      context: .
      dockerfile: docker/Dockerfile.ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
    depends_on:
      - ws
    restart: unless-stopped
    
  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - "8080:8080"
    restart: unless-stopped
