name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
push:
  branches:
    - main
jobs:


  Redeploy:
    runs-on: ubuntu-latest
    name: Redeploy evrything to production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ssh to server and deploy
        run: | 
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          ssh -i ~/ssh_key ec2-user@3.110.54.252
          cd ci-cd-
          git pull origin main
          pnpm install
          pnpm build
          pm2 restart all
        

      
